// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeGZTls4AJzzyHjmaCzWc5Vfw9KAFqaok',
    appId: '1:382217153328:web:acc9d313cb3644ad9676f5',
    messagingSenderId: '382217153328',
    projectId: 'messagerie-dart-project',
    authDomain: 'messagerie-dart-project.firebaseapp.com',
    storageBucket: 'messagerie-dart-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYihzS0sQqmIH3vZJuYdWv2Q2ntMERGts',
    appId: '1:382217153328:android:0d027b126dcd032b9676f5',
    messagingSenderId: '382217153328',
    projectId: 'messagerie-dart-project',
    storageBucket: 'messagerie-dart-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmd5WjLB8HHgCXn9u3W-eRH2xCg9Lesyg',
    appId: '1:382217153328:ios:22ba064eccba6e3e9676f5',
    messagingSenderId: '382217153328',
    projectId: 'messagerie-dart-project',
    storageBucket: 'messagerie-dart-project.firebasestorage.app',
    iosBundleId: 'com.example.messagerieDartProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmd5WjLB8HHgCXn9u3W-eRH2xCg9Lesyg',
    appId: '1:382217153328:ios:22ba064eccba6e3e9676f5',
    messagingSenderId: '382217153328',
    projectId: 'messagerie-dart-project',
    storageBucket: 'messagerie-dart-project.firebasestorage.app',
    iosBundleId: 'com.example.messagerieDartProject',
  );
}
